### ISSUE TITLE
2018.2 environment files missing 'name' field

### ISSUE THREAD

**Issue by joerleigh** [qiime2/environment-files#2]
The new yaml format environment files for version 2018.2 are missing the 'name' field. If you run conda env create with -p to specify an environment path, you cannot use -n to specify the name, and you thus get the error 'SpecNotFound: Can't process without a name'

**Comment by thermokarst** [comment]
Hi @joerleigh, the omission of the `name` field is deliberate, so that users can specify a name when creating their environment using the `-n` flag:

```bash
conda env create -n qiime2-2018.2 --file qiime2-2018.2-py35-osx-conda.yml
```

Using the `-p` flag is mutually exclusive to the name flag, because you are overriding the logical location on-disk. The following also works as expected with this env file:

```bash
conda env create -p /path/to/foo -f qiime2-2018.2-py35-osx-conda.yml
source activate /path/to/foo
```

Did I misunderstand your question? If so, please let me know! Thanks!

PS - make sure you are running the latest version of `conda` - I think 4.4.10 is latest at this time.

**Comment by joerleigh** [comment]
Sorry about this. I didn't realize that when using `conda env create` you can't just give it a url to the environment file like you could with `conda create` and the .txt environment files from previous versions of QIIME2. You actually have to download the environment file first and give conda a path to the file.
The error message `conda env create` gives when you try to give it a url is, confusingly, 'Can't process without a name.' I had 'fixed' the issue by downloading the environment file and sticking in a name, not realizing that it was the act of downloading the file that actually fixed the issue, not adding the name.

**Comment by thermokarst** [comment]
Ah! That makes sense! The lack of url support surprised us too --- maybe one of these days some @qiime2 devs will whip up a PR for the @conda folks that implements that feature. Thanks!
